version: '3.8'
services:

  # MySQL pentru User Service
  mysql-user:
    image: mysql:8.0
    container_name: mysql-user-service
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: user_service_db
      MYSQL_USER: user_service
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql
      - ./docker/mysql/user:/docker-entrypoint-initdb.d
    networks:
      - library-network

  # MySQL pentru Book Service
  mysql-book:
    image: mysql:8.0
    container_name: mysql-book-service
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: book_service_db
      MYSQL_USER: book_service
      MYSQL_PASSWORD: book123
    ports:
      - "3308:3306"
    volumes:
      - mysql_book_data:/var/lib/mysql
      - ./docker/mysql/book:/docker-entrypoint-initdb.d
    networks:
      - library-network

  # MySQL pentru Loan Service
  mysql-loan:
    image: mysql:8.0
    container_name: mysql-loan-service
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: loan_service_db
      MYSQL_USER: loan_service
      MYSQL_PASSWORD: loan123
    ports:
      - "3309:3306"
    volumes:
      - mysql_loan_data:/var/lib/mysql
      - ./docker/mysql/loan:/docker-entrypoint-initdb.d
    networks:
      - library-network

  # MySQL pentru Review Service
  mysql-review:
    image: mysql:8.0
    container_name: mysql-review-service
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: review_service_db
      MYSQL_USER: review_service
      MYSQL_PASSWORD: review123
    ports:
      - "3310:3306"
    volumes:
      - mysql_review_data:/var/lib/mysql
      - ./docker/mysql/review:/docker-entrypoint-initdb.d
    networks:
      - library-network

  # Redis pentru caching (opțional)
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - library-network

  # Adminer pentru administrarea bazelor de date
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8090:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql-user
    networks:
      - library-network
    depends_on:
      - mysql-user
      - mysql-book
      - mysql-loan
      - mysql-review

volumes:
  mysql_user_data:
  mysql_book_data:
  mysql_loan_data:
  mysql_review_data:
  redis_data:

networks:
  library-network:
    driver: bridge